apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datadog-analytics
  template:
    metadata:
      annotations:
        admission.datadoghq.com/enabled: "true"
      labels:
        app: datadog-analytics
    spec:
      containers:
      - name: datadog-analytics
        image: 269622523990.dkr.ecr.ap-northeast-2.amazonaws.com/datadog-analytics:c3dfd8c
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
        - name: DD_SERVICE
          value: datadog-analytics
        - name: DD_ENV
          value: prod
        - name: DD_VERSION
          value: c3dfd8c
        - name: DD_PROFILING_ENABLED
          value: "true"
        - name: DD_LOGS_INJECTION
          value: "true"
        - name: DD_GIT_REPOSITORY_URL
          value: "github.com/jungyoungseok/bitsfeed"
        - name: DD_GIT_COMMIT_SHA
          value: "c3dfd8c02c39a109c2c3c1efb7916c307da0ce01"
        - name: DD_APPSEC_ENABLED
          value: "true"
        - name: DD_IAST_ENABLED
          value: "true"
        - name: DD_APPSEC_SCA_ENABLED
          value: "true"
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: datadog-analytics
spec:
  selector:
    app: datadog-analytics
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP
