apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-consumer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-consumer
  template:
    metadata:
      labels:
        app: news-consumer
    spec:
      containers:
        - name: consumer                 
          image: 269622523990.dkr.ecr.ap-northeast-2.amazonaws.com/news-consumer:0f78efd
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: OPENAI_API_KEY
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: datadog-secrets
                  key: mongo-uri
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: datadog-secrets
                  key: kafka-uri
            - name: DD_ENV
              value: prod
            - name: DD_VERSION
              value: "0f78efd"
            - name: DD_DATA_STREAMS_ENABLED
              value: "true"
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_APPSEC_ENABLED
              value: "true"
            - name: DD_IAST_ENABLED
              value: "true"
            - name: DD_APPSEC_SCA_ENABLED
              value: "true"
            - name: DD_GIT_REPOSITORY_URL
              value: "github.com/jungyoungseok/bitsfeed"
            - name: DD_GIT_COMMIT_SHA
              value: "0f78efd13d32cbd176bf8e72c92ac245860bcbb9"
              


          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi