apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-consumer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-consumer
  template:
    metadata:
      labels:
        app: news-consumer
    spec:
      containers:
        - name: consumer                 
          image: 269622523990.dkr.ecr.ap-northeast-2.amazonaws.com/news-consumer:962bd76
          imagePullPolicy: Always
          ports:
          - containerPort: 8002
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: OPENAI_API_KEY
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: datadog-secrets
                  key: mongo-uri
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: datadog-secrets
                  key: kafka-uri
            - name: DD_ENV
              value: prod
            - name: DD_VERSION
              value: "962bd76"
            - name: PYTHONPATH
              value: "/opt/datadog/apm/library/python/ddtrace_pkgs/site-packages-ddtrace-py3.10-manylinux2014"
            - name: DD_DATA_STREAMS_ENABLED
              value: "true"
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_APPSEC_ENABLED
              value: "true"
            - name: DD_IAST_ENABLED
              value: "true"
            - name: DD_APPSEC_SCA_ENABLED
              value: "true"
            - name: DD_GIT_REPOSITORY_URL
              value: "github.com/jungyoungseok/bitsfeed"
            - name: DD_GIT_COMMIT_SHA
              value: "962bd762a3d17a17c58282c8f42fa0c4ae71d4df"
              
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: news-consumer-api
  namespace: default
spec:
  selector:
    app: news-consumer
  ports:
  - port: 8002
    targetPort: 8002
    protocol: TCP
    name: api
  type: ClusterIP