apiVersion: "datadoghq.com/v2alpha1"
kind: "DatadogAgent"
metadata:
  name: "datadog"
  namespace: datadog 
spec:
  global:
    clusterName: "datadog-news-cluster"
    registry: "public.ecr.aws/datadog"
    site: "datadoghq.com"
    tags:
      - "env:prod"
    credentials:
      apiSecret:
        secretName: "datadog-secret"
        keyName: "api-key"
  features:
    apm:
      instrumentation:
        enabled: true
        targets:
          - name: "default-target"
            namespaceSelector:
              matchNames:
                - "default"
            ddTraceVersions:
              java: "1"
              python: "3"
              js: "5"
              php: "1"
              dotnet: "3"
      # APM 활성화
      enabled: true
    logCollection:
      enabled: true
      containerCollectAll: true
    asm:
      threats:
        enabled: true
      sca:
        enabled: true
      iast:
        enabled: true
    cws:
      enabled: true
    cspm:
      enabled: true
    sbom:
      enabled: true
      containerImage:
        enabled: true
      host:
        enabled: true
    npm:
      enabled: true
    remoteConfiguration:
      enabled: true
    # Live Process Monitoring 활성화
    liveProcessCollection:
      enabled: true
  override:
    nodeAgent:
      env:
        # Health check 엔드포인트 trace 필터링
        - name: DD_APM_IGNORE_RESOURCES
          value: "GET /health,GET /ping,GET /status,GET /_health,GET /healthz,GET /readiness,GET /liveness"