apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog-news-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datadog-news-crawler
  template:
    metadata:
      labels:
        app: datadog-news-crawler
    spec:
      containers:
      - name: datadog-news-crawler
        image: 269622523990.dkr.ecr.ap-northeast-2.amazonaws.com/datadog-news-crawler:0e708dd
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: datadog-secrets
              key: mongo-uri
        - name: NEXT_PUBLIC_API_URL
          value: "https://k8s-default-datadogn-611e09ccff-13c50379c223eb66.elb.ap-northeast-2.amazonaws.com"
        - name: DD_SERVICE
          value: datadog-news-crawler
        - name: DD_ENV
          value: prod
        - name: DD_VERSION
          value: 0e708dd
        - name: DD_PROFILING_ENABLED
          value: "true"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

      - name: news-frontend
        image: 269622523990.dkr.ecr.ap-northeast-2.amazonaws.com/news-frontend:0e708dd
        ports:
        - containerPort: 3000
        env:
        - name: DD_SERVICE
          value: news-frontend
        - name: DD_ENV
          value: prod
        - name: DD_VERSION
          value: 0e708dd
        - name: DD_PROFILING_ENABLED
          value: "true"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"