apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog-news-crawler
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: datadog-news-crawler
  template:
    metadata:
      annotations:
        admission.datadoghq.com/enabled: "true"
      labels:
        app: datadog-news-crawler
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: datadog-news-crawler
      containers:
      - name: datadog-news-crawler
        image: 269622523990.dkr.ecr.ap-northeast-2.amazonaws.com/datadog-news-crawler:dfba3f9
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: datadog-secrets
              key: mongo-uri
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            secretKeyRef:
              name: datadog-secrets
              key: kafka-uri              
        - name: DD_SERVICE
          value: datadog-news-crawler
        - name: DD_ENV
          value: prod
        - name: DD_VERSION
          value: dfba3f9
        - name: DD_PROFILING_ENABLED
          value: "true"
        - name: DD_DATA_STREAMS_ENABLED
          value: "true"
        - name: DD_LOGS_INJECTION
          value: "true"
        - name: DD_GIT_REPOSITORY_URL
          value: "github.com/jungyoungseok/bitsfeed"
        - name: DD_GIT_COMMIT_SHA
          value: "dfba3f9dfe08c0e1a77287d3fe40d1d4b010993d"
        - name: DD_APPSEC_ENABLED
          value: "true"
        - name: DD_IAST_ENABLED
          value: "true"
        - name: DD_APPSEC_SCA_ENABLED
          value: "true"
        - name: DD_APM_INSTRUMENTATION_DEBUG
          value: "true"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

