apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kafka-crash-watcher-rolebinding
  namespace: kafka
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kafka
roleRef:
  kind: Role
  name: kafka-crash-watcher-role
  apiGroup: rbac.authorization.k8s.io
