apiVersion: v1
kind: Pod
metadata:
  name: kafka
  namespace: kafka
  labels:
    app: kafka
spec:
  containers:
    - name: kafka
      image: bitnami/kafka:3.5
      ports:
        - containerPort: 9092
      env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka.kafka.svc.cluster.local:9092
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_CFG_ZOOKEEPER_SESSION_TIMEOUT_MS
          value: "18000"    # default는 6000, 이 값을 늘려서 ZooKeeper 다운 시 여유를 줌
        - name: KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS
          value: "15000"    # ZooKeeper 연결 시도 timeout, 기본은 6000
        - name: KAFKA_CFG_ZOOKEEPER_SYNC_TIME_MS
          value: "2000"     # Kafka와 ZooKeeper 간 heartbeat sync
        - name: KAFKA_OPTS
          value: "-Dzookeeper.session.timeout=18000 -Dzookeeper.connection.timeout=15000"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
      livenessProbe:
        tcpSocket:
          port: 9092
        initialDelaySeconds: 30
        periodSeconds: 15
      readinessProbe:
        tcpSocket:
          port: 9092
        initialDelaySeconds: 10
        periodSeconds: 10
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 200m
      volumeMounts:
        - mountPath: /bitnami/kafka
          name: kafka-storage
  volumes:
    - name: kafka-storage
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
