apiVersion: batch/v1
kind: CronJob
metadata:
  name: kafka-crash-watcher
  namespace: kafka
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: restart-kafka-if-crashloop
            image: bitnami/kubectl:latest
            command:
              - /bin/bash
              - -c
              - |
                STATUS=$(kubectl get pod kafka -n kafka -o jsonpath='{.status.containerStatuses[0].state.waiting.reason}');
                if [[ "$STATUS" == "CrashLoopBackOff" ]]; then
                  kubectl delete pod kafka -n kafka;
                fi
          restartPolicy: OnFailure
