apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dotnet
  namespace: default
  labels:
    app: mysql-dotnet
    tier: database
    component: dotnet-sample
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql-dotnet
  template:
    metadata:
      labels:
        app: mysql-dotnet
        tier: database
        component: dotnet-sample
      annotations:
        admission.datadoghq.com/enabled: "false"
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dotnet-secrets
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: "dotnet_sample"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: dotnet-secrets
              key: mysql-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dotnet-secrets
              key: mysql-password
        - name: MYSQL_CHARSET
          value: "utf8mb4"
        - name: MYSQL_COLLATION
          value: "utf8mb4_unicode_ci"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        - name: mysql-config
          mountPath: /etc/mysql/conf.d
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -h localhost -u root -p$MYSQL_ROOT_PASSWORD"
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -h localhost -u root -p$MYSQL_ROOT_PASSWORD"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        securityContext:
          runAsNonRoot: false
          allowPrivilegeEscalation: true
      volumes:
      - name: mysql-storage
        emptyDir: {}
      - name: mysql-config
        configMap:
          name: mysql-dotnet-config
      securityContext:
        fsGroup: 999
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
  labels:
    app: mysql-dotnet
    tier: database
    component: dotnet-sample
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: mysql-dotnet
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-dotnet-config
  namespace: default
  labels:
    app: mysql-dotnet
    tier: database
data:
  mysql.cnf: |
    [mysqld]
    # Basic Settings
    default_authentication_plugin = mysql_native_password
    
    # Character Set / Collation
    character-set-server = utf8mb4
    collation-server = utf8mb4_unicode_ci
    init_connect = 'SET NAMES utf8mb4'
    
    # Connection Settings
    max_connections = 200
    wait_timeout = 28800
    interactive_timeout = 28800
    
    # InnoDB Settings
    innodb_buffer_pool_size = 256M
    innodb_log_file_size = 64M
    innodb_flush_log_at_trx_commit = 2
    innodb_lock_wait_timeout = 50
    
    # Query Cache (disabled for MySQL 8.0)
    # query_cache_type = OFF
    
    # Logging
    general_log = 0
    slow_query_log = 1
    slow_query_log_file = /var/lib/mysql/mysql-slow.log
    long_query_time = 2
    
    # Binary Logging
    log_bin = mysql-bin
    binlog_format = ROW
    expire_logs_days = 7
    max_binlog_size = 100M
    
    # Security
    local_infile = 0
    
    # Performance Schema
    performance_schema = ON
