apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-frontend
  template:
    metadata:
      annotations:
        admission.datadoghq.com/enabled: "true"
      labels:
        app: news-frontend
    spec:
      containers:
        - name: news-frontend
          image: 269622523990.dkr.ecr.ap-northeast-2.amazonaws.com/news-frontend:67e1cdb
          ports:
          - containerPort: 3000
          env:
            - name: DD_SERVICE
              value: news-frontend
            - name: DD_ENV
              value: prod
            - name: DD_VERSION
              value: 67e1cdb
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: NEWS_API_URL
              value: "http://datadog-news-crawler:8000"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_GIT_REPOSITORY_URL
              value: "github.com/jungyoungseok/bitsfeed"
            - name: DD_GIT_COMMIT_SHA
              value: "67e1cdb613ea08d6170de106d86f3e798ba9c703"
            - name: DD_APPSEC_ENABLED
              value: "true"
            - name: DD_IAST_ENABLED
              value: "true"
            - name: DD_APPSEC_SCA_ENABLED
              value: "true"
            - name: DD_APM_INSTRUMENTATION_DEBUG
              value: "true"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
