apiVersion: v1
kind: Service
metadata:
  name: news-frontend-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: news-frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000   # 고정 포트 사용
