apiVersion: v1
kind: Pod
metadata:
  name: zookeeper
  namespace: kafka
  labels:
    app: zookeeper
spec:
  containers:
    - name: zookeeper
      image: bitnami/zookeeper:3.8
      ports:
        - containerPort: 2181
      env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: kafka
spec:
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
