apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog-news-crawler
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JungYoungseok/bitsfeed.git
    targetRevision: main
    path: datadog-crawler/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
