apiVersion: v1
kind: Service
metadata:
  name: datadog-news-crawler-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  selector:
    app: datadog-news-crawler
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
